/** this ensures - in all profiles and modes,, that something very odd didnt happen ( certain bus types are volatile... ... inbuilt is stable...
but other types of volume, via connection types are not stable... you have to assuem at any point it can be lost... */
export function assert_disk_vol_id() {}

/// this checks the last snapshot matches teh current state... due to dodgy manufacturers... OS can go a bit weird... ( and yes its all OS... 
//// Windows/Linux is the only OS that can handle a disk farm of the size I have ==> props.. shame on the rest of you...
export function assert_polling_disk_vol_ids() {}

/// some os and disk controllers will conflict via teh same manufacturer id.. which means together with connection problems someting mad happens...
