/* asserts that somehow volume IDs and other IDs generated aren't clashing in the heaps... since this is a catastrophic condition... */
// however there are some allowable controller ids ... if its present two have the same... it could be its a lazy manufacturer getting their rom id wrong...
// in this scenario its almost impossible without user input .... TODO (matt): i have to think about this in terms, of interface/type/purpose... 
