/// when severity is great enough decide to assert that a controller still exists in its virtual state ( yes this is a thing )
////  controllers are pluggable and can disappear or the os decided the data was so weird, it decided to drop and it crashed... 

//// depsite windows winnning the USB race for example - its not actually stable and is flawed...
//// OSX is not supported since it doesnt handle this level of a farm
//// Linux i am undecided on ... 
