/** instead of just saying using x dep or fs-extra.. we do this uniform and with signals that control how the library responds...
 * we have two aims:- it works forever and it works for very bad stuff telling you, and it copes with change... ie,, its reliable
 * forever... */

// calls to fs. are through this... they also go in the invocation / manifest log.. the user logs,, are just you...

// depending on the profile mods, the level of checking for operations, and hashes,,,, is directed too here, hence why i want it
// we aren't messing around - a file must be the same - and nothing should be lost... 
