/** 
 * all os operations, are not user mode log, but included in the manifest log, that always happens everytime the library is used... 
 * this logs exactly what commands ( until perhaps making a proper zig library for this ) have been used and with what... 
 */ 
