/** this file uses a snapshot of the system logs, and compares it to what we recorded... where we can reliable determine that we arrived at the correct results */

// this file is not for locally run builds, it runs when the distributed version is used, and by default via the +resident mod, or as a resident from default...
// this check only happens once, and is flagged into the context being used...

