/**
 * Node.js lockdown environment generator (`gen_lockdown_nodejs.mjs`)
 * generates boot wrapper scripts and environment configurations (`--frozen-intrinsics`)
 * that natively lock down and freeze all built-in JavaScript prototypes (`Object.prototype`,
 * `Array.prototype`, `Function.prototype`) right when V8 boots.
 *
 * this allows us to maintain `var` mechanical sympathy across our code while relying on
 * Node.js C++/V8 engine-level enforcement against prototype pollution across long-running resident processes.
 *
 * usage:
 *   node local/tool/gen_lockdown_nodejs.mjs --target windows --out local/sh/run_resident.cmd
 */

// 1p
import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname } from 'node:path'

// 2p
import { arg_parse_cli, arg_get_opt } from '../../src-mjs.dev/lib/arg/libcd_arg.mjs'

export function gen_lockdown_script(options= {}) {
    var target= arg_get_opt(options, 'target', process.platform === 'win32' ? 'windows' : 'linux')
    var entry= arg_get_opt(options, 'entry', 'src-mjs.main/libcd_main.mjs')
    var extra_flags= arg_get_opt(options, 'flags', '--frozen-intrinsics --no-warnings')

    if (target === 'osx' || target === 'darwin') {
        throw new Error('[LOCKDOWN] OSX/Darwin target is not supported (`doc/maintainer/guard_and_promotion.md`).')
    }

    if (target === 'windows' || target === 'win32') {
        return [
            '@echo off',
            'rem generated by local/tool/gen_lockdown_nodejs.mjs',
            'rem natively freezes Object.prototype and all V8 built-in intrinsics at boot time',
            'set NODE_OPTIONS=' + extra_flags,
            'node "' + entry + '" %*'
        ].join('\r\n') + '\r\n'
    }

    // target is linux, nix, or posix
    return [
        '#!/usr/bin/env sh',
        '# generated by local/tool/gen_lockdown_nodejs.mjs (' + target + ')',
        '# natively freezes Object.prototype and all V8 built-in intrinsics at boot time',
        'export NODE_OPTIONS="' + extra_flags + '"',
        'exec node "' + entry + '" "$@"'
    ].join('\n') + '\n'
}

if (process.argv[1] && process.argv[1].endsWith('gen_lockdown_nodejs.mjs')) {
    var cli= arg_parse_cli(process.argv.slice(2))
    var opts= cli.options || {}
    var out_path= arg_get_opt(opts, 'out', null)

    var script_content= gen_lockdown_script(opts)
    if (out_path) {
        var dir= dirname(out_path)
        if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
        writeFileSync(out_path, script_content, { encoding: 'utf8', mode: 0o755 })
        process.stdout.write('[LOCKDOWN] Generated boot script at: ' + out_path + '\n')
    } else {
        process.stdout.write(script_content)
    }
}
