/** this ensures - in all profiles and modes, that something very odd didn't happen ( certain bus types are volatile... ... built-in is stable...
but other types of volume, via connection types are not stable... you have to assume at any point it can be lost... */
export function assert_disk_vol_id() {}

/// this checks the last snapshot matches the current state... due to dodgy manufacturers... OS can go a bit weird... ( and yes it's all OS... 
//// Windows/Linux is the only OS that can handle a disk farm of the size I have ==> props.. shame on the rest of you...
export function assert_polling_disk_vol_ids() {}

/// some OS and disk controllers will conflict via the same manufacturer ID.. which means together with connection problems something mad happens...
