/* asserts that somehow volume IDs and other IDs generated aren't clashing in the heaps... since this is a catastrophic condition... */
// however there are some allowable controller ids ... if its present two have the same... it could be its a lazy manufacturer getting their rom id wrong...
// i have a type of usb interface, and two western digital ssd, but they clash.. windows doesn't understand it... 
// in this scenario its almost impossible without user input .... TODO (matt): i have to think about this in terms, of interface/type/purpose... 
// however I think a database of this condition from auto clash heuristics to a cloud endpoint might be useful but a V3 thing 
// otherwise the library has to break a boundary to ask the user and then needs to assume they understand what's going on .. ..