/// when severity is great enough decide to assert that a controller still exists in its virtual state ( yes this is a thing )
////  controllers are pluggable and can disappear or the OS decided the data was so weird, it decided to drop and it crashed... 

//// despite windows winning the USB race for example - it's not actually stable and is flawed...
//// OSX is not supported since it doesn't handle this level of a farm
//// Linux i am undecided on ... 
