/** defines conditions that pause or reduce the library activity */

// in windows we would need to monitor apps, defender, and deployments... via service queries I suppose? or actually for each it's a hook to interrupt timer...
// we can use the new node way of doing this... and augment it with knowledge of the disk farm ... 
